service: botobbot

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1

functions:
  challenge:
    handler: handler.challenge
    events:
      - http:
          path: webhook
          method: get
          cors: true

  receive:
    handler: handler.receive
    events:
      - http:
          path: webhook
          method: post
          cors: true
